Add bookings
MarychevDmitry/java-shareit pull request #2
Opened 2024-02-20 22:08 UTC by MarychevDmitry

Реализован функционал описанный в  ТЗ 14.
Давлен функционал бронирования.

2024-02-21 22:12 UTC, alexache requested changes

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
Для чего этот класс? Это не ДТО, но и не модель данных?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @Autowired
Лучше не использовать dependency injection на поле, а в конструкторе

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        isBookingDtoValid(bookingDto);
Почему не через аннотации валидации? Иначе для чего @Validated на классе без использования валидаций

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingDto.getStart() == null || bookingDto.getEnd() == null) {
такие валидации логичнее делать в контроллере/на уровне ДТО

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return toBookingDto(booking);
возвращается ли айди сохраненной сущности?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
getUserById() делает тоже самое?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (itemRepository.findByUserId(userId).isEmpty()) {
Нужна ли такая проверка?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getBooker().getId().equals(userId) || booking.getItem().getUser().getId().equals(userId)) {
Может тогда делать getBookingByIdAndBookerId() выше?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/comment/entity/Comment.java
> +@Data
Лишняя аннотация

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/exception/RequestNotFoundException.java
> +        log.error("ERROR: " + message);
Не очень хорошая правктика логгировать из конструктора исключений

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +public interface ItemDao {
этот и следующий класс уже не нужны?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/entity/Item.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
Не вижу полей, которые включены

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        checkUser(userId);
Не проще ли всегда делать по аналогии с методом выше .findById().orElseThrow()?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            item.setRequest(itemRequestRepository.findById(itemDto.getRequestId()).get());
Тоже дублирование запроса

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!itemRepository.findByUserId(ownerId).contains(item)) {
Почему не взять вещь по айди и проверить владельца? Или просто взять вещь по айди и владельцу?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemRepository.delete(getItemById(itemId));
Почему бы не удалить по айди?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private User getUserById(Long userId) {
Приватные методы должны быть после публичных

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Optional<Booking> lastBooking = bookingRepository.findFirstByItemIdAndStatusAndStartBeforeOrderByStartDesc(itemDto.getId(), Status.APPROVED, LocalDateTime.now());
Запросы к базе из цикла (выше цикл по списку вещей) под запретом

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<Comment> commentList = commentRepository.findAllByItemId(itemDto.getId());
Еще один запрос к базе внутри цикла

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private User requester;
Откуда-то неДТО поля

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/entity/ItemRequest.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
Какое поле?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto createUser(@RequestBody UserDto userDto) {
Валидации не требуются?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/UserDao.java
> +public interface UserDao {
Используется ли этот класс?

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/entity/User.java
> +@Data
Нельзя использовать с JPA сущностями

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        isUserDtoValid(userDto);
Валидации - задача контроллера

2024-02-21 22:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String HEADER_USER_ID = Constants.HEADER_USER_ID;
Почему просто не использовать Constants.HEADER_USER_ID?

2024-03-02 17:32 UTC, MarychevDmitry commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return toBookingDto(booking);
Да, возвращается.

2024-03-04 05:53 UTC, alexache approved these changes

2024-03-04 05:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select b from Booking b where b.item.user.id = ?1")
Такой запрос тоже можно сделать без @Query в духе findAllByItem_UserId

2024-03-04 05:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/entity/Item.java
> +@EqualsAndHashCode
На сущностях базы нельзя автогенерировать эти методы  (по всем полям)- будет работать некорректно

2024-03-11 20:40 UTC, merged